### ISSUE TITLE
just information about old and new version of mhddos_proxy

### ISSUE THREAD

**Issue by kazamov** [alexnest-ua/auto_mhddos_alexnest#15]
Repository "https://github.com/porthole-ascend-cinnamon/mhddos_proxy.git" does not exist. It causes failing the installing of the tool. There is another repo "https://github.com/porthole-ascend-cinnamon/mhddos_proxy_releases". It contains the installable packages. I used the command to install the tool on Linux.

**Comment by alexnest-ua** [comment]
runner.sh doesnt have any line with https://github.com/porthole-ascend-cinnamon/mhddos_proxy.git, it is updated 2 years ago to use https://github.com/porthole-ascend-cinnamon/mhddos_proxy_releases. Maybe u try to run setup.sh which is out-dated and dont neccessary, because everything is running in runner.sh. 

or maybe u try to run setup-arch.sh file which is also out-dated, + I didnt create it by mysefl, it was a pull request.

anyway thanks, for the feedback, I deleted setup files!

if there will be some other problems, please, inform me!
also u can check this repo https://github.com/porthole-ascend-cinnamon/mhddos_proxy_releases to use it directly, but dont forget about "screen" function for running it 24/7!
